### ISSUE TITLE
If you set the "firstDay" option to 7, "nextMonthDay" will not be displayed.

### ISSUE THREAD

**Issue by asapping99** [sinankeskin/Lightpick#4]
**Describe the bug**
If you set the "firstDay" option to 7, "nextMonthDay" will not be displayed.

**To Reproduce**

**Expected behavior**
![image](https://user-images.githubusercontent.com/10718850/74803573-bb9e6400-5320-11ea-9b6b-3e04b3965460.png)

In the attached image, you need to modify the code as follows:

source code >> var nextMonth = moment(day),
          nextDays = 7 - nextMonth.isoWeekday() + opts.firstDay;

modify code >> var nextMonth = moment(day),
          nextDays = 7 - nextMonth.isoWeekday();

**Comment by sinankeskin** [comment]
Hi.

I've checked and I see your point but seems like your solution is not working.

I'll investigate deeply when I have free time.

Thank you.

**Comment by sinankeskin** [comment]
Please use https://github.com/wakirin/Litepicker.

Thank you.
