### ISSUE TITLE
I have a suggestion to post.

### ISSUE THREAD

**Issue by asapping99** [sinankeskin/Lightpick#5]
The "nextMonth, prevMonth" function seems to work by the number of "numberOfMonths". I would like to have the option to specify the number of months of movement for "nextMonth" and "prevMonth".
Or, I would like to have the option to move by "numberOfMonths" and move by only one month.
In fact, all you need is to move only once a month.
For example, if it is 'February and March', I want to express it as 'March and April'.
Currently, February and March are represented as April and May.

**Comment by sinankeskin** [comment]
Hi. Please use https://github.com/wakirin/Litepicker

Thank you.
